/** Metadata of column header */
export type ColumnHeader = {
  /** Column name */
  name: string

  /**
   * Index in data row.
   */
  index: number

  isDeleted: boolean
}

/** Data row */
export type TableRow = Array<unknown | null>

export type TableChunksSource = {
  header: ColumnHeader[]
  getSourceGenerator: () => AsyncGenerator<TableRow[]>
}

/**
 * Table row transformer. Gets batch of rows and returns transformed batch.
 */
export type TableChunksTransformer = (
  rowsChunkInfo: TableChunksSource
) => Promise<TableChunksSource>

export type PrependHeadersStyle = 'COLUMN_NUM' | 'EXCEL_STYLE'

export type TableTransfromConfig = {
  /** Transformers */
  transforms: TableChunksTransformer[]

  /**
   * **Prepended header style.**
   *
   * If option is specified, then autogenerated header row will be prepended to data rows.
   *
   * Options:
   * - `COLUMN_NUM` - add headers like `Col1`, `Col2`, ...
   * - `EXCEL_STYLE` - add headers like `A`, `B`, ..., `AX`, ...
   *
   * Use this option if table has't headers.
   */
  prependHeaders?: PrependHeadersStyle
}
